[package]
name = "arrata-lib"
version = "0.1.2"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
bitcode = { version = "0.6.9", default-features = false, features = ["derive"] }
rand = { version = "0.10.2", default-features = false, features = [
  "thread_rng",
] }
dioxus-stores = "0.7.10"

[features]
dioxus = []
